### PR TITLE
Fix for Laravel 5

### PR DESCRIPTION
**Pull request by Paic**

### CODE REVIEW

**Comment by gugglegum** [comment]
Why this pull request with change in 1 line is not merged within more than 2 months? @razorpay you did a great job to reanimate and support this orphaned project. But without this PR your whole project is useless. It can't be used with current version of Laravel 5.4.28.

@Paic, Could you apply your PR in your fork if @razorpay will not respond? I'll use your repo then.

**Comment by gugglegum** [comment]
@razorpay could you please also add "Issues" section for this project to allow people register issues?

**Comment by captn3m0** [comment]
@gugglegum Added issues.

**Comment by gaurav1068** [comment]
@Paic Can you please add Description here, what issue were you facing and how this fixes it. Because We are already using this repo in our laravel5.4 app

**Comment by gaurav1068** [comment]
@gugglegum Can you explain What is the issue that you are facing, or create an Issue and we look into it

**Comment by gugglegum** [comment]
@gaurav1068 Yes, sure. I'm trying to make a clean install of this package as described in README. I added provider and alias in `config/app.php` as described. Then generated config file by command `php artisan config:publish razorpay/slack` and configured file. But then on any attempt to call any method of `\Slack` class I got an error. For example, on `\Slack::send('Hello world!');` I got:
```
PHP Fatal error: Uncaught ReflectionException: Class razorpay.slack does not exist in C:\..(path to project)..\vendor\laravel\framework\src\Illuminate\Container\Container.php:729
Stack trace:
#0 C:\..(path to project)..\vendor\laravel\framework\src\Illuminate\Container\Container.php(729): ReflectionClass->__construct('razorpay.slack')
#1 C:\..(path to project)..\vendor\laravel\framework\src\Illuminate\Container\Container.php(608): Illuminate\Container\Container->build('razorpay.slack')
#2 C:\..(path to project)..\vendor\laravel\framework\src\Illuminate\Container\Container.php(575): Illuminate\Container\Container->resolve('razorpay.slack')
#3 C:\..(path to project)..\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(728): Illuminate\Container\Container->make('razorpay.slack')
#4 ... in C:\Users\paul\Workspace\activefreedom\projects\marketplaces-api\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 729
```

Also I use `barryvdh/laravel-ide-helper` package to add support of code completion in my IDE. And when i generate helper file by `php artisan ide-helper:generate` I'm getting:
```
Exception: Class razorpay.slack does not exist
Skipping \Razorpay\Slack\Laravel\Facade.
Exception: Class razorpay.slack does not exist
Skipping \Razorpay\Slack\Laravel\Facade.
A new helper file was written to _ide_helper.php
```

If I manually make the change in `vendor\razorpay\slack-laravel\src\ServiceProviderLaravel5.php` as described in Pull Request and replace
```
        $this->app->singleton('slack', function ($app) {
```
to
```
        $this->app->singleton('razorpay.slack', function ($app) {
```
All started to work just fine. And IDE-helper too. I didn't go deep into this problem, but I think this is some compatibility issue with new version of laravel 5.4.

Can you explain how you use this package in your project and how it's still working? Maybe you're use 5.4, but not 5.4.28 version? Or maybe you use it in some different way?

**Comment by gaurav1068** [comment]
@gugglegum we are using laravel 5.4.21 will test on version 5.4.28 and will get back on this

**Comment by gaurav1068** [comment]
@gugglegum We were using in the following way
$app = App::getFacadeRoot();
$app['slack']->send('Hello world!');

which worked, but it should have been worked in the way mentioned in README, fixed that released a new tag 1.4.0 for that 

Closing this PR as it is fixed in another way, @Paic Thanks for the PR, but fixed it in another way

**Comment by gugglegum** [comment]
I confirm that 1.4.0 version works fine now.

**Pull request closed without merging**
